tasks:
  - init: |
      chmod 755 .
      docker pull composer
      docker-compose pull
    command: |
      docker run --rm --tty --volume $PWD:/app --user $(id -u):$(id -g) composer install --ignore-platform-reqs
      docker-compose up
vscode:
  extensions:
    - ms-azuretools.vscode-docker
