tasks:
  - init: |
      chmod 755 .
      docker pull composer
      docker-compose pull
      docker-compose build www
    command: sh ./.devcontainer/postCreateCommand.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - johnbillion.vscode-wordpress-hooks
