version: '3.6'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: s9f6sd759r32r7f0dsf5673894956
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
    - db
    ports:
    - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: s9f6sd759r32r7f0dsf5673894956
      PMA_USER: root
      PMA_PASSWORD: s9f6sd759r32r7f0dsf5673894956
  mail:
    # Port 1025 for SMTP.
    image: mailhog/mailhog:latest
    ports:
    - 8081:8025
    - 8083:1025
  www:
    depends_on:
    - db
    - mail
    image: wordpress:latest
    volumes:
    - ".:/var/www/html/wp-content/plugins/simple-smtp"
    ports:
    - 80:80
    - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: s9f6sd759r32r7f0dsf5673894956
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ALLOW_MULTISITE', true );